fieldLayouts:
  a83f0a2b-a55a-4230-a38f-55e9328b3c08:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: fc1a1deb-9b8e-4d38-9702-f0ab4c608260
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 52ddd013-6f84-448d-8d0b-0ce88df90727 # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b760dddb-ac16-4597-b54f-1330a3f62f34
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9a0a6eb4-4adc-49dc-82f1-e27208388163 # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 82515140-7ff5-4596-bed3-c37f64f51aba
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 54892d51-6af3-47f5-a6de-7f94ea88fcc7 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 833c875d-98d7-427c-be79-ef93db5fda31
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 673008cf-d7c5-4aea-aa1a-b9e4b77a09b9
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: f7d56ebf-8a70-409c-9292-78cc1a05a95e # Blog
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
