columnSuffix: null
contentColumnType: string
fieldGroup: a6cb0b36-6e63-4910-aeb5-39091b8dcfaf # Common
handle: divisionLogoClass
instructions: null
name: 'Division Logo Class'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: string
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
