columnSuffix: vrkuybxe
contentColumnType: string
fieldGroup: a6cb0b36-6e63-4910-aeb5-39091b8dcfaf # Common
handle: email
instructions: null
name: Email
searchable: false
settings:
  placeholder: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
