changedFieldIndicator: 6524735
field: 37934a56-4514-46fd-b0b9-253e8bf86921 # Division Member
fieldLayouts:
  3901d315-adfd-44fd-8906-dab2b51e2e1c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 868df16e-1857-42c9-9640-36aaba6424a8 # Nama Member
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b6985d11-8125-4676-a14e-f9da2a83fa9f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a9e90adf-8bc5-4757-a48d-1029cbca4a23 # Jabatan
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df309ec0-d969-481b-b57d-94dcf4c94595
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 56ac2769-bf4b-479e-89cb-6f9d12e26216 # Member Photos
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d6935b98-9829-42c1-9910-e1df6f7fd5dc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 09ea3e70-5d0b-4acc-92fc-09e2f7197d4d
        userCondition: null
fields:
  56ac2769-bf4b-479e-89cb-6f9d12e26216: # Member Photos
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: memberPhotos
    instructions: null
    name: 'Member Photos'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:2f7d1591-436d-4912-830a-229b8653f5b1' # Featured Image
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:2f7d1591-436d-4912-830a-229b8653f5b1' # Featured Image
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  868df16e-1857-42c9-9640-36aaba6424a8: # Nama Member
    columnSuffix: jolahdli
    contentColumnType: string
    fieldGroup: null
    handle: namaMember
    instructions: null
    name: 'Nama Member'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: string
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a9e90adf-8bc5-4757-a48d-1029cbca4a23: # Jabatan
    columnSuffix: qelyfzjn
    contentColumnType: string
    fieldGroup: null
    handle: jabatan
    instructions: null
    name: Jabatan
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: string
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
