defaultPlacement: end
enableVersioning: false
handle: division
name: Division
propagationMethod: all
siteSettings:
  1d9ea0ea-8e61-4532-82d8-57929963a966: # Coder-Web
    enabledByDefault: true
    hasUrls: true
    template: division/_entry
    uriFormat: 'division/{slug}'
type: channel
