defaultPlacement: end
enableVersioning: false
handle: news
name: News
propagationMethod: all
siteSettings:
  1d9ea0ea-8e61-4532-82d8-57929963a966: # Coder-Web
    enabledByDefault: true
    hasUrls: true
    template: news/_entry
    uriFormat: 'news/{slug}'
type: channel
